language: python
python:
  - "3.6.6"
services:
  postgresql
env:
  global:
    - DJANGO_SETTINGS_MODULE="partners.settings"
addons:
  postgresql: '9.5'
# command to install dependencies
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt codecov
before_script:
  - psql -c "CREATE DATABASE travis_ci_db;" -U postgres
  - python manage.py migrate --noinput
# command to run tests
script:
  - pycodestyle partners/ core/ products/ pedidos/
  - pyflakes partners/ core/ products/ pedidos/
  - coverage run manage.py test -v 2
after_success:
  - codecov