version: "3.3"

services:
  database:
    container_name: zumaq-partners
    image: postgres
    restart: always
    volumes:
    - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=zumaq-partners
      - POSTGRES_USER=zumaq-partners
    ports:
      - 5432:5432