# Generated by Django 3.0.5 on 2020-04-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacoesMoedas',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cny', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
