# Generated by Django 3.1.2 on 2020-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201021_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_secret_key',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
