# Generated by Django 3.2.6 on 2021-08-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacoesmoedas',
            name='cny',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cotacoesmoedas',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
