# Generated by Django 3.1.2 on 2020-10-22 03:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201021_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_secret_key',
            field=models.UUIDField(default=core.models.make_secret),
        ),
    ]
