# Generated by Django 3.1.2 on 2020-10-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201022_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_secret_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='api_view',
        ),
    ]
