# Generated by Django 3.1.2 on 2020-10-22 03:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201022_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_secret_key',
            field=models.CharField(default=core.models.make_secret, max_length=36),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_view',
            field=models.BooleanField(default=False, verbose_name='Habilitar API programática'),
        ),
    ]
