# Generated by Django 3.1.2 on 2020-10-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201022_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_secret_key',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
