# Generated by Django 2.1.7 on 2019-02-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20190214_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
    ]
