# Generated by Django 2.1.7 on 2019-02-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20190214_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile', verbose_name='parceiro'),
        ),
    ]
