# Generated by Django 2.1.5 on 2019-01-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Código do produto')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição do produto')),
                ('pago_na_china', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Preço de custo em ¥')),
                ('reminmbi', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Reminmbi ¥')),
                ('dolar_cotado', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Em reais (R$)')),
                ('compra_do_cambio', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Em reais (R$)')),
                ('impostos_na_china', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Impostos na China (%)')),
                ('porcentagem_importacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentagem Importação (%)')),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coeficidente (%)')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
    ]
