# Generated by Django 2.1.5 on 2019-01-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190118_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcoeficienteitens',
            name='parceiro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.CustomCoeficiente'),
        ),
    ]
