# Generated by Django 2.1.5 on 2019-01-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190118_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcoeficienteitens',
            name='produto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Produto'),
        ),
    ]
