# Generated by Django 2.1.5 on 2019-01-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190118_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('codigo', 'descricao'), 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
