# Generated by Django 2.1.5 on 2019-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190130_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcoeficiente',
            name='coeficiente_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coeficidente (%)'),
        ),
    ]
