# Generated by Django 2.2 on 2019-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190214_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
