# Generated by Django 2.2.4 on 2019-08-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190408_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosAtacado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade atacado')),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coeficidente (%)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
