# Generated by Django 2.2.4 on 2019-08-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_produtosatacado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutosAtacado',
            new_name='ProdutoAtacado',
        ),
    ]
