# Generated by Django 2.2.4 on 2019-08-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190802_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoatacado',
            options={'verbose_name': 'Produto atacado', 'verbose_name_plural': 'Produtos atacado'},
        ),
    ]
