# Generated by Django 2.2.6 on 2019-10-02 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_auto_20190802_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProdutoAtacado',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade atacado')),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coeficidente (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.Produto')),
            ],
            options={
                'verbose_name': 'historical Produto atacado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduto',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('codigo', models.CharField(db_index=True, max_length=60, verbose_name='Código do produto')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição do produto')),
                ('pago_na_china', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Preço de custo em ¥')),
                ('reminmbi', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Reminmbi ¥')),
                ('dolar_cotado', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Em reais (R$)')),
                ('impostos_na_china', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Impostos na China (%)')),
                ('porcentagem_importacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentagem Importação (%)')),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coeficidente (%)')),
                ('imagem', models.URLField(blank=True, default='https://via.placeholder.com/150', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical produto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomCoeficienteItens',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coeficidente (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parceiro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.CustomCoeficiente')),
                ('produto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.Produto')),
            ],
            options={
                'verbose_name': 'historical custom coeficiente itens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomCoeficiente',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('coeficiente_padrao', models.DecimalField(decimal_places=2, default=0.5, max_digits=10, verbose_name='Coeficidente padrão (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parceiro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical custom coeficiente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
