# Generated by Django 3.0.5 on 2020-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_historicalcustomcoeficiente_historicalcustomcoeficienteitens_historicalproduto_historicalprodutoatac'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduto',
            name='dolar_automatico',
            field=models.BooleanField(default=True, help_text='Se selecionado o \n                                           valor de venda será baseado na \n                                           cotação do dolar mais recente ao \n                                           inves do dolar cotado', verbose_name='Dolar automático'),
        ),
        migrations.AddField(
            model_name='produto',
            name='dolar_automatico',
            field=models.BooleanField(default=True, help_text='Se selecionado o \n                                           valor de venda será baseado na \n                                           cotação do dolar mais recente ao \n                                           inves do dolar cotado', verbose_name='Dolar automático'),
        ),
    ]
