# Generated by Django 3.0.5 on 2020-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200415_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduto',
            name='dolar_automatico',
            field=models.BooleanField(default=True, help_text='Se selecionado o\n                                           valor de venda será baseado na\n                                           cotação do dolar mais recente ao\n                                           inves do dolar cotado', verbose_name='Dolar automático'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dolar_automatico',
            field=models.BooleanField(default=True, help_text='Se selecionado o\n                                           valor de venda será baseado na\n                                           cotação do dolar mais recente ao\n                                           inves do dolar cotado', verbose_name='Dolar automático'),
        ),
    ]
