# Generated by Django 3.1.7 on 2021-03-15 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_auto_20200416_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customblocked')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.produto')),
            ],
            options={
                'unique_together': {('parceiro', 'produto')},
            },
        ),
    ]
