# Generated by Django 4.1 on 2022-08-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210420_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcustomcoeficiente',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical custom coeficiente', 'verbose_name_plural': 'historical custom coeficientes'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomcoeficienteitens',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical custom coeficiente itens', 'verbose_name_plural': 'historical custom coeficiente itenss'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical produto', 'verbose_name_plural': 'historical produtos'},
        ),
        migrations.AlterModelOptions(
            name='historicalprodutoatacado',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Produto atacado', 'verbose_name_plural': 'historical Produtos atacado'},
        ),
        migrations.AlterField(
            model_name='historicalcustomcoeficiente',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomcoeficienteitens',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprodutoatacado',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
