# Generated by Django 4.1.3 on 2022-11-24 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_alter_historicalcustomcoeficiente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduto',
            name='fora_de_estoque',
            field=models.BooleanField(default=False, help_text='Se selecionado, exibe o\n                                          produto, mas não permite comprar.', verbose_name='Fora de estoque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fora_de_estoque',
            field=models.BooleanField(default=False, help_text='Se selecionado, exibe o\n                                          produto, mas não permite comprar.', verbose_name='Fora de estoque'),
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produto')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Listas de espera',
            },
        ),
        migrations.AddConstraint(
            model_name='waitinglist',
            constraint=models.UniqueConstraint(fields=('parceiro', 'produto'), name='parceiro com esse produto já existe'),
        ),
    ]
